### PR TITLE
Imporovemt

### PR DESCRIPTION
**Pull request by oatmealine**
I pimprove Your program Willy sir.

### CODE REVIEW

**Comment by oatmealine** [comment]
Ples accept my pull requ est It will Improve program by 100%

**Comment by oatmealine** [comment]
And you will be able to use it,with fast and blazing;

**Comment by oatmealine** [comment]
It will go fast!.Please add it;willycrespo

**Comment by WillyCrespo** [comment]
Yeah sure,added to releases but also check my profile too :)

**Pull request closed without merging**
